### ISSUE TITLE
Bug when selected ratio is not saved in the "columns with a ratio of " section

### ISSUE THREAD

**Issue by LittleHamster** [siteorigin/siteorigin-panels#317] opened 2016-12-03 06:44 UTC
The selected ratio is not saved in the "Columns with a ration of" selection when viewing the ratio. 
example: Create a row / Edit Row / Set Ratio to Golden / Save and publish
when editing the same row again, ratio is set to even but it is golden ratio

 
<img width="1113" alt="screen shot 2016-12-03 at 1 43 28 am" src="https://cloud.githubusercontent.com/assets/10330481/20857423/fdddeb20-b8f9-11e6-8576-41c272825161.png">

**Comment by gregpriday** [comment] 2016-12-03 06:48
Thanks for reporting. This is a duplicate of: https://github.com/siteorigin/siteorigin-panels/issues/230

**Closed by gregpriday** 2016-12-03 06:48 UTC
Labels: duplicate
