### ISSUE TITLE
Long list with various characters doesn't display at all in Page Builder

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#197] opened 2016-03-30 14:11 UTC
The below list doesn't display when inserted into Page Builder using a SO Editor or Text widget. 

Reference thread: https://siteorigin.com/thread/editor-wont-load-if-contains-certain-words/

```
<ul><li>Rascal scooter</li>
<li>Nice treadmill</li>
<li>RCA and Sony 42″ <strong>FLAT SCREEN TVS</strong></li>
<li>Samsung 32″ flat screen TV</li>
<li>Heat Surge electric fireplace</li>
<li>Electrolux Oxygen canister vacuum</li>
<li>Hoover Windtunnel vacuum Bissell and Kenmore carpet cleaner</li>
<li>Water cooler</li>
<li>Farberware convection/broil oven</li>
<li>Ninja Pro blenders</li>
<li>Crosley old style stereo record player with CD</li>
<li>Musical instruments including Artisan Steel lap guitar, Kay guitar and clarinet</li>
<li>Inland stain glass grinder</li>
<li>Aviation headset David Clark model H10-30 in original box</li>
<li>Records</li>
<li>Lot CD’s including Country</li>
<li>Amethyst and other crystals</li>
<li>Arnold, Nebraska advertising stoneware bail handle jar</li>
<li>Watt #62 Rooster pitcher</li>
<li>Slag glass small table lamp</li>
<li>Temp-Tations “Old World” bakeware</li>
<li>Sets silver plate flatware including Oneida “Queen Bess II”</li>
<li>Sets porcelain dinnerware including Nasco “Rose Ann”</li>
<li>Hamilton 17j men’s wrist watch</li>
<li>“Raimond” pewter coffee set</li>
<li>Axel Tornrose illustrations</li>
<li>Frank Gordon original watercolors</li>
<li>Virginia Artist limited edition prints including Carmen Sherbeck (artist proofs), Anita Bilkins, Dewey Sizemore, Marsha Heatwole, Page Huff Dillion, etc.</li>
<li>1891 Waynesboro, Virginia facsimile maps</li>
<li>Large collection limited edition prints including Bill Hurd, John Morton Barber, Rick Rush, etc.</li>
<li>1971 Aberdeen-Angus prints</li>
<li>1981 UVA Ralph Sampson poster</li>
<li>Wooden frames for Moss collector plates</li>
<li>Hamilton Beach food processor</li>
<li>Vintage Sunbeam mixer on stand</li>
<li>Vintage colored Pyrex</li>
<li>Fenton holiday green American Christmas Tree set with box</li>
<li>Books including C.E. May’s “Life Under 4 Flags”, 1930’s Raggedy Ann books by Gruelle, 1950’s yearbooks, etc.</li>
<li>Wild Fowl carving magazines</li>
<li>Nascar plaques, lamp, cars, etc.</li>
<li>Three tables modern dolls including GI Joe</li>
<li>Mt. Crawford, Virginia calendar plate</li>
<li>Mid-Century bar set including decanter</li>
<li>Two pieces Mid-Century German art pottery</li>
<li>Baltimore Pear pattern glass table set</li>
<li>Longaberger baskets</li>
<li>Tole table lamps</li>
<li>Christmas including Dept. 56, Clothtique Santas, etc.</li>
<li>35mm cameras with lenses</li>
<li>Plus more</li>
</ul>
```

**Comment by Misplon** [comment] 2016-03-30 15:00
SiteOrigin Custom Post Type Builder seems to be the plugin causing this in my installation.

**Comment by braamgenis** [comment] 2016-03-31 09:15
I don't think the CPT Builder has been published on the wordpress.org directory, but I checked it anyway and with CPT Builder installed, it seems to be working fine for me in both SO Editor and Text widget.

It sounds like it might not be sanitizing properly because the words that cause it could be considered unsafe, e.g. '**drop** leaf **table**' (SQL) and '**CD**' (Bash command). So perhaps something to do with configuration on the hosted server they're using?

**Comment by braamgenis** [comment] 2016-04-01 08:39
Closing as not a bug.

**Closed by braamgenis** 2016-04-01 08:39 UTC
Labels: invalid
