### ISSUE TITLE
Content from Page Builder being copied into post content regardless of plugin setting

### ISSUE THREAD

**Issue by SteveS123** [siteorigin/siteorigin-panels#114] opened 2015-11-02 22:32 UTC
If you navigate to Settings > Page Builder and uncheck "Copy content from Page Builder to post content" you can expect this to behave properly when making updates to the Page Builder from the admin, that is not using the Live Editor.  But should you make a change to the Page Builder from within the Live Editor the post content gets populated regardless of the setting.

**Comment by SteveS123** [comment] 2015-11-02 22:37
Actually scratch that, it seems to be copying content to the posts editor using the Live Editor or not.

**Comment by braamgenis** [comment] 2016-01-07 10:06
Hi @SteveS123 

This seems to be working fine for me. Could you provide steps to reproduce the issue you're seeing?
Thanks.

**Comment by SteveS123** [comment] 2016-01-07 18:13
Sure-

1. Create a new page.
2. Click the "Page Builder" tab above the editor.
3. Add a widget.
4. Click "Switch to Editor" and choose "Ok" at the "Would you like to clear your Page Builder content and revert to using the standard visual editor?" prompt

You should then see your widget HTML inside the standard editor.

**Comment by braamgenis** [comment] 2016-01-08 08:15
Ah, ok. Thanks @SteveS123. We'll look into this soon.

**Comment by braamgenis** [comment] 2016-02-22 09:10
Resolved by GH-163

**Closed by braamgenis** 2016-02-22 09:10 UTC
Labels: bug, priority-2

**Comment by SteveS123** [comment] 2016-02-22 09:20
Thank you!
