### ISSUE TITLE
Improve compatibility with TipTopPress's Category Posts Widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#518] opened 2018-04-02 13:57 UTC
[TipTopPress's Category Posts Widget](https://wordpress.org/plugins/category-posts/)
[Related Forum Thread](https://wordpress.org/support/topic/cant-use-plugin-inside-a-widget/) (ignore the review portion).
[Slack](https://siteorigin.slack.com/archives/C02SYBBH2/p1522594262000035)

**Comment by DanielFloeter** [comment] 2018-04-02 21:39
It is a bit frustrated for us. After release the patch version we get first user issues that the code don't work with Firefox.
Exactly this is what I described with not secure code. It is very hard for us to write here better code.

This is our code we implement, but we will very happy, if you implement also the WordPress trigger and actions that we can get rid of this commit again:
https://github.com/tiptoppress/category-posts-widget/commit/6162862e4a85a721342f2ad8fb17228e2a9ad84b

How can I reach with my slack account  (@tiptoppress) our channel?

**Comment by DanielFloeter** [comment] 2018-04-04 14:57
A new user rating write exactly what we mean with unsecure code.

"... I found a bug with their new patch, which was an incompatibility issue with ACF repeater field .... you can’t test compatibility with every plugin out there, even though ACF is huge! ..." ([https://wordpress.org/support/topic/support-is-excellent-9/](https://wordpress.org/support/topic/support-is-excellent-9/))

With the implementation for the compativility to your SiteOrigin Page Builder plugin we get a but with another widget and have to patch this again ... ggggrhhh!

Now it works all well, but we want only to test against WordPress versions. That's enough tests. All not testes code in depth is what we don't want.

**Comment by gregpriday** [comment] 2019-02-12 11:03
Hi @DanielFloeter - apologies for missing this issue before. I'm just going over everything on Github and came across it.

I'm going to go over everything and test with your plugin to figure out how we can get everything compatible between SiteOrigin Page Builder and your plugin.

**Comment by DanielFloeter** [comment] 2019-02-25 22:51
@gregpriday The problem is about the Javascript framework 'Select2'. If it is included with two different versions it cause an Javascript error.
Now we get an similar issue about Avada Theme and the Fusion Builder. And I also guess YOAST use Select2.
May we should ask the Select2 team how to avoid such version collisions, if WordPress is used and many plugins and widgets use different Select2 references?

**Comment by Misplon** [comment] 2019-07-28 15:30
Hi Daniel. Thanks for your feedback. We're going to close this issue for the moment. If any compatibility issues arise in the future, please, let us know. 

All the best.

**Closed by Misplon** 2019-07-28 15:30 UTC
Labels: enhancement, priority-3
