### ISSUE TITLE
Widget added in 2.9.7 isn't working in 2.10.0

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#635] opened 2019-01-31 10:23 UTC
[This widget](https://drive.google.com/a/siteorigin.com/uc?id=163-pdrhimyf_iPZ4fA1k0eaTIeQWUUPo) will stop working after updating from 2.9.7. The widget code is from [this article](https://www.wpbeginner.com/wp-tutorials/how-to-create-a-custom-wordpress-widget/).

This issue, during my tests, doesn't appear to happen with PHP 5 and only occured for me when using PHP 7.3.1. The user stated he was able to replicate this in 7.1 so there may be a weird setup requirement.

**Comment by braamgenis** [comment] 2019-01-31 19:38
I'm unable to replicate using PHP 7.1 or PHP 7.3. Although the issue is very likely to be related to the funky case differences between the string used to register and the class name and I'm not sure there's anything we can do about that. 😕

**Comment by AlexGStapleton** [comment] 2019-01-31 22:11
Unfortunately, I can't seem to replicate this issue anymore. This issue is super inconsistent. 😞

**Comment by gregpriday** [comment] 2019-02-10 06:01
Closing for now, please open this up if it comes up again and we can get some more details.

**Closed by gregpriday** 2019-02-10 06:01 UTC
Labels: bug, priority-2
