### ISSUE TITLE
Improve <!-- nextpage --> support

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#340] opened 2017-02-07 10:41 UTC
`<!-- nextpage -->` is very unreliable and only really works if one or two widgets are present at the most.

[WordPress.com reference](https://en.support.wordpress.com/nextpage/) (there's no reliable WordPress.org link)

**Comment by gregpriday** [comment] 2017-03-20 16:21
Duplicate of https://github.com/siteorigin/siteorigin-panels/issues/290

**Closed by gregpriday** 2017-03-20 16:21 UTC
Labels: duplicate
