### ISSUE TITLE
Unable to disable some built-in plugins

### ISSUE THREAD

**Issue by sharifzadesina** [siteorigin/siteorigin-panels#534] opened 2018-05-09 15:05 UTC
For example I am not able to disable "Post Carousel":
It is disabled here:
![2018-05-09_19-30-37](https://user-images.githubusercontent.com/15300551/39822543-11da3e00-53c0-11e8-9c71-db9dbfce49a9.png)
But it is still shown here:
![2018-05-09_19-31-51](https://user-images.githubusercontent.com/15300551/39822580-29a2f7ca-53c0-11e8-87c7-3b9a1f10b222.png)

**Comment by AlexGStapleton** [comment] 2018-05-10 04:16
Hi,

This is definitely an issue this is a duplicate of another issue. Unfortunately, I can't seem to find it at the moment so I'm going to leave this at the moment but it will likely be closed at a later date in favor of the other issue.

**Comment by Misplon** [comment] 2018-05-11 08:29
Hi @sharifzadesina 

Thanks for raising this. We'll have it resolved in the next Page Builder update.

https://github.com/siteorigin/siteorigin-panels/pull/451
https://github.com/siteorigin/siteorigin-panels/pull/451

**Comment by sharifzadesina** [comment] 2018-05-11 08:30
@Misplon Thank you.

**Comment by gregpriday** [comment] 2018-06-13 07:42
We're going to leave the defaults as is to avoid any possible confusion, but you can remove these teaser widgets by navigating to `Settings > Page Builder` in your WordPress admin. Under the `Widgets` tab, disable `Recommended Widgets`.

**Closed by gregpriday** 2018-06-13 07:42 UTC
Labels: bug, priority-2
