### ISSUE TITLE
Prebuilt layout: Add Hook to disable Prebuilt layout button / functionality (button and overall functionality)

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#218] opened 2016-04-25 20:52 UTC
Use case: I wish to restrict the layout directory to CUSTOM USER ROLE and currently I'm unable to do so.

**Comment by gregpriday** [comment] 2017-03-19 14:01
Duplicate of https://github.com/siteorigin/siteorigin-panels/issues/219

**Closed by gregpriday** 2017-03-19 14:01 UTC
Labels: enhancement, priority-2
