### ISSUE TITLE
Conflict with polylang cause problem with custom-post permalinks.

### ISSUE THREAD

**Issue by matmar-91** [siteorigin/siteorigin-panels#258] opened 2016-07-12 10:38 UTC
I have registered custom-post type gallery. My permalinks structure is /%category%/%post_name%/. All works well until last pagebuilder update - now custom-post singles go to 404 error. 

I've narrowed it down to this commit: 
https://github.com/siteorigin/siteorigin-panels/commit/0cb18c5836bc74b424fdaa8b9846e30b4e890aee

Changing action back to init and saving permalinks resloves problem with rewrites. 
I think this can be conflict with polylang plugin because disabling it and saving permalinks also resolves problem, **but before last pagebuilder update it works with both plugins enabled**.

Here is respective issue on polylang github: 
https://github.com/polylang/polylang/issues/35

**Comment by Chouby** [comment] 2016-07-20 12:44
I confirm that this commit introduced the conflict with Polylang. 

The problem is inside the function `register_widgets()` at line https://github.com/siteorigin/siteorigin-panels/blob/2.4.10/inc/sidebars-emulator.php#L66

Indeed `url_to_post_id()` calls `$wp_rewrite->wp_rewrite_rules();` which will get the rewrite rules option and update it if is empty (which is the case when flushing rewrite rules).

Thus, when flushing rewrite rules, they are evaluated in 'widget_init' hook (equivalent to 'init' priority 1), while most plugins will register custom post types and custom taxonomies in 'init' hook with priority 10. 
Rewrite rules are evaluated too soon and broken.

**Comment by gregpriday** [comment] 2016-07-22 10:08
Hi everyone. Thanks for all the feedback, we're trying to recreate this on our side.

@matmar-91 That commit was actually a revert of a change we'd made not too long ago. We had to revert the change because it was causing issues with other plugins.

I'll update this issue when we have more information, or if there's any other information we need.

**Comment by Misplon** [comment] 2016-07-22 10:09
Hi @matmar-91 

If possible, please could you install Duplicator plugin and backup your install and then upload the Duplicator instance to Dropbox or Drive and send us the link on support@siteorigin.com? That way we can setup a mirror copy of your install and hopefully get to the bottom of the issue.

**Comment by matmar-91** [comment] 2016-07-25 09:39
Yes, no problem. I will do that soon. Thanks for your help!

**Comment by Misplon** [comment] 2016-07-25 10:57
Awesome, appreciate it.

**Comment by gregpriday** [comment] 2016-08-30 07:20
We've all had a look at this issue here and unfortunately haven't been able to recreate it yet. Has anyone been able to create a quick Duplicator backup for us? This would be a huge help in figuring out what's causing the issue.

**Comment by gregpriday** [comment] 2016-08-30 08:30
As a temporary fix for this issue, we'll make it possible to disable sidebar emulation entirely.

https://github.com/siteorigin/siteorigin-panels/commit/ad004d05205db418216d6d2029f98f5c90dd117d

This will be available in the next update. It'll be a setting in the General tab.

**Comment by Chouby** [comment] 2016-08-30 12:15
I reproduce the issue like this:

On a fresh WP site, activate Polylang + Page Builder + WooCommerce (any other plugin using custom post type or taxonomies would have the same issue). You don't eve need to run the WooCommerce wizard. 

In Settings > Languages, create a language.
In Settings > Languages > Settings > Custom post types and taxonomies, check "product" and Save changes.

Add a WooCommerce product. Publish. Visit the link. You get a 404.

I also get the same issue on a multisite, without Polylang but when network activating Yoast SEO. When you network activate Yoast SEO, it deletes the rewrite rules on all sites. Then you directly go visiting a product page, it is 404 because the rewrite rules are evaluated to soon, before WooCommerce registered its post types.

**Comment by gregpriday** [comment] 2016-08-30 12:37
Thanks @Chouby. I was able to recreate the issue using your steps, although just navigating to Settings > Permalinks (flushing the rewrite rules), was enough to fix the issue. I'll investigate some more though.

**Comment by Chouby** [comment] 2016-08-30 12:47
In my tests, navigating to Settings > Permalinks doesn't work if Page Builder and Polylang are activated together as Polylang still doesn't add its rewrite rules filters for custom post types and taxonomies.

If Yoast SEO and Page Builder are activated together, then navigating to Settings > Permalinks (on all sites of the multisite install) is sufficient, because with Yoast, the issue occurs only at the time it is network activated or deactivated. Yoast doesn't break when rules are flushed using another way (unlike Polylang).

**Comment by gregpriday** [comment] 2016-08-30 13:12
Something I have noticed is that the sidebars emulator isn't actually necessary on admin requests. @Chouby, if you have a second, could you check the latest develop version of Page Builder? There's a chance this would fix the issue.

https://github.com/siteorigin/siteorigin-panels/commit/95264202154831b4efece4ca89d29172e7b12346

**Comment by Chouby** [comment] 2016-08-30 14:40
This is a good step but only a partial fix. At least, this will stop blocking users to keep Polylang and Page Builder together, although they may have to manually flush the rewrite rules to make this happen. I explain:

This fixes the conflict with Polylang when calling `flush_rewrite_rules()`, because in most cases this function is called on admin side.

This doesn't fix the issue when activating / deactivating Polylang or when network activating / network deactivating Yoast SEO.

In fact, in these cases, we don't use `flush_rewrite_rules()`, but `delete_option( 'rewrite_rules' )`. Rewrite rules are thus not evaluated on the current page but on the next visited page (which may not be on admin side).

The reason is the same for both plugins: we try to handle correctly the rewrite rules at network activation / deactivation. There is just one difference: Yoast handles differently single activation and network activation while Polylang uses the same code (which explains why Polylang breaks at single site activation wile Yoast breaks only at network activation).

While making searches on these kind of issues, I just found an interesting post of Jeremy Felt which explains all the issues we have with rewrite rules at network activation: see https://jeremyfelt.com/2015/07/17/flushing-rewrite-rules-in-wordpress-multisite-for-fun-and-profit/. I also opened a ticket on the topic some months ago: https://core.trac.wordpress.org/ticket/32471

**Comment by Chouby** [comment] 2016-08-31 09:15
An attempt to solve the conflict with plugins using `delete_option( 'rewrite_rules' )` at activation / deactivation: https://core.trac.wordpress.org/ticket/37892

**Comment by gregpriday** [comment] 2016-08-31 17:12
Thanks for all the help @Chouby. It's been a huge help. I've been testing things with `delete_option( 'rewrite_rules' )` and it seems like this change might do the trick - https://github.com/siteorigin/siteorigin-panels/commit/31cf0e3525c4d6ab93b068a7b0ad0a65921e52be

Basically the extra check `( ! get_option('permalink_structure') || get_option('rewrite_rules') )` is disabling the sidebars emulator when there is a permalink structure, but there isn't a stored rewrite_rules. This gives WordPress the chance to regenerate and store the rewrite rules before calling `url_to_postid`.

A different solution would be to use the same check to decide if Page Builder registers the widgets on `widgets_init` or later - on `init`.

**Comment by Chouby** [comment] 2016-09-01 13:03
Great! I saw that the changes have been released in v2.4.14. On my side, I made a small change to make sure that rewrite rules filters are added only once (as before) but after 'wp_loaded' has been fired (to be released in v2.0.4 next week). With both your modifications and mine, the conflict should now be solved :) Thanks!

**Comment by gregpriday** [comment] 2016-09-01 13:11
Phew. Glad it's fixed - that was a tricky issue. Thanks again for the help and keep up the great work on your plugin. It's always been the one we've recommended to our users.

**Closed by gregpriday** 2016-09-01 13:11 UTC
Labels: bug

**Comment by avrillica** [comment] 2016-09-07 16:18
Can somebody briefly explain the result of all the conversation and explain how we should solve this problem?
I disabled sidebar emulator and everything is now working fine, but is there any better-permanent solution for this?

**Comment by gregpriday** [comment] 2016-09-07 16:55
@avrillica - we both fixed the issue and added a setting to disable the sidebar emulator just in case an issue like this comes up again. You can leave the sidebar emulator enabled and the issue will still be fixed.

**Comment by avrillica** [comment] 2016-09-07 17:03
No! If I enable the emulator, Permalinks stop working. That is why I asked in the first place.

**Comment by Chouby** [comment] 2016-09-07 17:39
Are you using Polyang 2.0.4?

**Comment by avrillica** [comment] 2016-09-07 18:42
Yes I am using Polylang 2.0.4 and Pagebuilder 2.4.15
