### ISSUE TITLE
SiteOrigin Layout: Headline and Hero display issues after editing Features widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#636] opened 2019-01-31 22:10 UTC
[Slack](https://siteorigin.slack.com/archives/C02SYBBH2/p1548972044001700)

A few users have reported using the SiteOrigin Layout Block issue where the SiteOrigin Headline widget stops displaying and the SiteOrigin Hero widget stops functioning correctly (not being able to change slide). Two of the users have reported that this issue occurs afte rediting the Features widget. This issue only occurs while using the SiteOrigin Layout block and doesn't occur while using the Classic Editor.

SiteOrgin Headline widget output looks like this:
![](https://vgy.me/94vcma.png)

Widget settings are in tact and preview without issue when using Block Preview.

Two possible related error logs (from Debug Bar):

```
Warning (Suppressed)    Invalid argument supplied for foreach() 2   
-
get_template_part('content','page')
wp-content/themes/generatepress/page.php:31
locate_template()
wp-includes/general-template.php:155
load_template('wp-content/themes/generatepress/content-page.php')
wp-includes/template.php:647
the_content()
wp-content/themes/generatepress/content-page.php:45
apply_filters('the_content')
wp-includes/post-template.php:240
do_blocks()
wp-includes/class-wp-hook.php:286
render_block()
wp-includes/blocks.php:251
WP_Block_Type->render()
wp-includes/blocks.php:193
SiteOrigin_Panels_Compat_Layout_Block->render_layout_block()
wp-includes/class-wp-block-type.php:109
SiteOrigin_Panels_Renderer->render()
wp-content/plugins/siteorigin-panels/compat/layout-block.php:96
SiteOrigin_Panels_Renderer->render_row()
wp-content/plugins/siteorigin-panels/inc/renderer.php:325
SiteOrigin_Panels_Renderer->render_cell()
wp-content/plugins/siteorigin-panels/inc/renderer.php:731
SiteOrigin_Panels_Renderer->render_widget()
wp-content/plugins/siteorigin-panels/inc/renderer.php:805
SiteOrigin_Panels_Renderer->the_widget()
wp-content/plugins/siteorigin-panels/inc/renderer.php:845
SiteOrigin_Widget->widget()
wp-content/plugins/siteorigin-panels/inc/renderer.php:539
wp-content/plugins/so-widgets-bundle/widgets/headline/tpl/default.php:3
Plugin: so-widgets-bundle
```

```
Notice (Suppressed) Undefined index: videos 2   
-
get_template_part('content','page')
wp-content/themes/generatepress/page.php:31
locate_template()
wp-includes/general-template.php:155
load_template('wp-content/themes/generatepress/content-page.php')
wp-includes/template.php:647
the_content()
wp-content/themes/generatepress/content-page.php:45
apply_filters('the_content')
wp-includes/post-template.php:240
do_blocks()
wp-includes/class-wp-hook.php:286
render_block()
wp-includes/blocks.php:251
WP_Block_Type->render()
wp-includes/blocks.php:193
SiteOrigin_Panels_Compat_Layout_Block->render_layout_block()
wp-includes/class-wp-block-type.php:109
SiteOrigin_Panels_Renderer->render()
wp-content/plugins/siteorigin-panels/compat/layout-block.php:96
SiteOrigin_Panels_Renderer->render_row()
wp-content/plugins/siteorigin-panels/inc/renderer.php:325
SiteOrigin_Panels_Renderer->render_cell()
wp-content/plugins/siteorigin-panels/inc/renderer.php:731
SiteOrigin_Panels_Renderer->render_widget()
wp-content/plugins/siteorigin-panels/inc/renderer.php:805
SiteOrigin_Panels_Renderer->the_widget()
wp-content/plugins/siteorigin-panels/inc/renderer.php:845
SiteOrigin_Widget->widget()
wp-content/plugins/siteorigin-panels/inc/renderer.php:539
SiteOrigin_Widget_Base_Slider->render_template()
wp-content/plugins/so-widgets-bundle/widgets/hero/tpl/default.php:3
SiteOrigin_Widget_Base_Slider->render_frame()
wp-content/plugins/so-widgets-bundle/base/inc/widgets/base-slider.class.php:164
SiteOrigin_Widget_Hero_Widget->get_frame_background()
wp-content/plugins/so-widgets-bundle/base/inc/widgets/base-slider.class.php:229
wp-content/plugins/so-widgets-bundle/widgets/hero/hero.php:318
Plugin: so-widgets-bundle
```

**Comment by AlexGStapleton** [comment] 2019-02-03 23:07
Another user reported this issue. I was able to _temporarily_ restore a SiteOrigin Headline widget by opening the widget and adjusting any text field values. Not too sure if it helps but I thought I would mention it just in case.

**Comment by braamgenis** [comment] 2019-02-04 00:14
Thanks for the extra info. I've already found the cause and implemented a fix for this issue, which will go out with the next release. Yeah, a workaround for the issue would be simply to open and close a widgets form (for each widget experiencing this issue) before saving.

**Closed** 2019-02-05 18:41 UTC
Labels: bug, priority-1
