### ISSUE TITLE
YOAST SEO 'fleschReadingEase' with Page Builder by Siteorigin

### ISSUE THREAD

**Issue by nextend** [siteorigin/siteorigin-panels#499] opened 2017-12-19 09:27 UTC
Related ticket in Yoast SEO: https://github.com/Yoast/wordpress-seo/issues/8517

Page Builder by SiteOrigin version: 2.6.0
Yoast SEO version: 5.9.3

Steps to reproduce the issue:
- On an empty page
- Switch to the "Readability" pane in Yoast SEO
- Add  any WordPress widget to the page - For example "Archives"
- Switch to "Enter focus keyword" pane in Yoast SEO
- Switch back to the "Readability" pane in Yoast SEO
- Then you will see the error: "An error occurred in the 'fleschReadingEase' assessment"

Note: Visual editor and SiteOrigin elements are fine with this test.

HTML value of the page which fails on the test:
```
<div id="pl-7692"  class="panel-layout" ><div id="pg-7692-0"  class="panel-grid panel-no-style" ><div id="pgc-7692-0-0"  class="panel-grid-cell"  data-weight="1" ><div id="panel-7692-0-0-0" class="so-panel widget widget_sow-editor panel-first-child" data-index="0" ><div class="so-widget-sow-editor so-widget-sow-editor-base">
<div class="siteorigin-widget-tinymce textwidget">
	<p>jrtzjrtzj</p></div>
</div></div><div id="panel-7692-0-0-1" class="so-panel widget widget_black-studio-tinymce widget_black_studio_tinymce" data-index="1" data-style="{&quot;background_display&quot;:&quot;tile&quot;}" ><div class="textwidget"><p>rtjrtzjrtzj rtzjrtz jrtzj rtzjrt zjrtj </p></div></div><div id="panel-7692-0-0-2" class="so-panel widget widget_black-studio-tinymce widget_black_studio_tinymce" data-index="2" data-style="{&quot;background_display&quot;:&quot;tile&quot;}" ><div class="textwidget"><p>rtjrtzjrtzj rtzjrtz jrtzj rtzjrt zjrtj </p></div></div><div id="panel-7692-0-0-3" class="so-panel widget widget_archives widget_archive panel-last-child" data-index="3" >[siteorigin_widget class="WP_Widget_Archives"]<input type="hidden" value="{&quot;instance&quot;:[],&quot;args&quot;:{&quot;before_widget&quot;:&quot;&lt;div id=\&quot;panel-7692-0-0-3\&quot; class=\&quot;so-panel widget widget_archives widget_archive panel-last-child\&quot; data-index=\&quot;3\&quot; &gt;&quot;,&quot;after_widget&quot;:&quot;&lt;\/div&gt;&quot;,&quot;before_title&quot;:&quot;&lt;h3 class=\&quot;widget-title\&quot;&gt;&quot;,&quot;after_title&quot;:&quot;&lt;\/h3&gt;&quot;,&quot;widget_id&quot;:&quot;widget-0-0-3&quot;}}" />[/siteorigin_widget]</div></div></div></div>
```

**Comment by Misplon** [comment] 2017-12-19 15:14
Hi @nextend 

Thanks for reporting this. Sorry for the hassle. I've chatted to @braamgenis about this. He let me know that:

_This is being caused by Yoast doing an AJAX call to fetch processed shortcodes and replace the raw shortcode with the processed one in the content. However because it's out of the normal context it doesn't perform some escaping we require and so it doesn't succeed when trying to replace the raw shortcode and instead just removes the shortcode tags as unrecognized._

We don't have a solution at the moment but will deploy a fix as soon as we're able.

**Comment by joedguarino** [comment] 2018-01-30 01:01
This is still plaguing one of my sites. If I can help in any way, let me know. This is for current version of Yoast Premium: v6.2 and SiteOrigin Bundle: v1.11.3

**Comment by Misplon** [comment] 2018-01-30 08:21
Hi @joedguarino. Wish we had an update for you. We know what's causing the issue but haven't been able to find a workaround as of yet. We haven't given up and will update as soon as we've looked at further options to resolve.

**Comment by braamgenis** [comment] 2018-02-07 09:20
I've done some deeper digging and it took me a while, but I believe I've found the real cause for this issue. Unfortunately the problem lies in the Yoast SEO plugin, so I've commented on the related issue at Yoast with my findings. Hopefully it will help them to resolve the issue.

https://github.com/Yoast/YoastSEO.js/issues/1346#issuecomment-363706282

**Comment by Misplon** [comment] 2018-04-19 17:27
Hi everyone. Thanks for your efforts. I'm closing this as we'll refer to the issue on the Yoast repo as linked above in Braam's reply and explanation.

**Comment by gregpriday** [comment] 2018-06-06 19:21
Resolved with https://github.com/siteorigin/siteorigin-panels/commit/d526fabf3b8f9def0713ebe36ae26ccad5dc77de - huge thanks to @nextend for the code.

**Closed by gregpriday** 2018-06-06 19:21 UTC
Labels: bug, priority-1
